### PR TITLE
Fixes #1

### LINKED ISSUE #1: Send call for filling out the contact form for data contributors once users register
After creating an account http://data.opendevelopmentmekong.net/user/register, users should receive an email indicating that they should fill pout the contact form exposed under https://opendevelopmentmekong.net/contribute-data/ otherwise they won't be able to contribute with data.

## Sub-tasks

- [x] @prustar will draft text to include in email
- [x] @acorbi will implement

### PR DESCRIPTION
**Pull request by acorbi**

### CODE REVIEW

**Comment by acorbi** [comment]
@prustar The email notification for newly registered user is deployed on PP for testing.

You can head to https://data.pp.opendevelopmentmekong.net/user/register (remember to logout first) and create a test user with some email address you own and can use for testing purposes.

Following email will be sent to that address:

screenshot from 2017-09-13 15-18-44

NOTE that the duplicated salutation should not appear anymore.

**Comment by prustar** [comment]
@acorbi just did it but haven't received the email yet - how long should it take?

**Comment by acorbi** [comment]
@prustar I tested it 3 times successfully:
- are you trying on PP? https://data.pp.opendevelopmentmekong.net/user/register
- have you checked your spam folder?

**Comment by prustar** [comment]
https://data.pp.opendevelopmentmekong.net/user/prustar

here's my user account check for yourself. My inbox is empty?

**Comment by acorbi** [comment]
have you checked your spam folder?

**Pull request merged**
